INSERT INTO
    [CourseLeaf_Contacts].[dbo].[banner_userinfo]
    (
        load_id,
        uin,
        pidm,
        first_name,
        preferred_first_name,
        middle_name,
        last_name,
        name_suffix,
        email_address,
        netid,
        campus_domain,
        max_activity_date
        insert_timestamp
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )