INSERT INTO
    [CourseLeaf_Contacts].[dbo].[banner_courses]
    (
        load_id,
        term,
        course,
        subject_code,
        course_no,
        course_title,
        college,
        dept_no,
        control_code,
        course_id,
        course_start_term,
        course_end_term,
        course_effective_term,
        status,
        insert_timestamp
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )