INSERT INTO
    [CourseLeaf_Contacts].[dbo].[banner_terms]
    (
        load_id,
        term_code,
        term_name_full,
        term_name,
        term_start_date,
        term_end_date,
        insert_timestamp
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )