SELECT 
	COLUMN_NAME
FROM 
	<DATABASE>.INFORMATION_SCHEMA.COLUMNS
WHERE 
	TABLE_NAME = ?
	AND TABLE_CATALOG = '<DATABASE>'
	AND TABLE_SCHEMA = '<SCHEMA>'
	AND COLUMN_NAME <> 'id'
	AND COLUMN_NAME <> 'load_id'
	AND COLUMN_NAME <> 'insert_timestamp'
ORDER BY
	ORDINAL_POSITION
;