INSERT INTO
    [CourseLeaf_Contacts].[dbo].[banner_departments]
    (
        load_id,
        dept_no,
        dept_name,
        college,
        college_name,
        insert_timestamp
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    )