SELECT
	STVTERM_CODE AS term_code,
	STVTERM_DESC AS term_name_full,
	CASE
		WHEN STVTERM_DESC LIKE '%Academic Year%' THEN STVTERM_DESC
		WHEN STVTERM_DESC LIKE '%Winter%' THEN SUBSTR(STVTERM_DESC, 1, INSTR(STVTERM_DESC, ' ', 8))
		ELSE SUBSTR(STVTERM_DESC, 1, INSTR(STVTERM_DESC, ' -'))
	END AS term_name
FROM
	SATURN.STVTERM
WHERE
	SUBSTR(STVTERM_CODE, 1, 1) = '1' -- only Urbana-Champaign terms
	AND SUBSTR(STVTERM_CODE, 2, 5) <> '99999' -- exclude end of time term code
	AND STVTERM_DESC NOT LIKE '%Global Campus%'
	AND STVTERM_DESC NOT LIKE '%Summer2%'
ORDER BY
	STVTERM_CODE
;